#!/bin/bash
param1=$@
BASEDIR=$(dirname "$0")
PROJECT_NAME=${param1// /_}
mkdir -p $PROJECT_NAME
cd $PROJECT_NAME
PROJECT=$(dirname "$_")

# Create folders
mkdir -p src
mkdir -p dist
mkdir -p types
mkdir -p test
mkdir -p tools

# Copy package.json and fill the template string
cp "$BASEDIR/newts_assets/ts.package.json" "$PROJECT/package.json"
sed -i "" "s/{{NAME}}/$PROJECT_NAME/g" "$PROJECT/package.json"

# Copy other assets
cp "$BASEDIR/newts_assets/index.ts" "$PROJECT/src"
cp "$BASEDIR/newts_assets/README.md" "$PROJECT"
sed -i "" "s/{{NAME}}/$PROJECT_NAME/g" "$PROJECT/README.md"

cp "$BASEDIR/newts_assets/tsconfig.json" "$PROJECT"
cp "$BASEDIR/newts_assets/tslint.json" "$PROJECT"
cp "$BASEDIR/newts_assets/gitignore" "$PROJECT/.gitignore"
cp "$BASEDIR/newts_assets/editorconfig" "$PROJECT/.editorconfig"
cp "$BASEDIR/newts_assets/travis.yml" "$PROJECT"
cp "$BASEDIR/newts_assets/test/index.test.ts" "$PROJECT/test"
cp "$BASEDIR/newts_assets/tools/semantic-release-prepare.ts" "$PROJECT/tools"

# Install modules
npm i typescript @types/node ts-node-dev \
tslint tslint-config-prettier tslint-config-standard \
jest @types/jest ts-jest \
husky commitizen cz-conventional-changelog lint-staged \
semantic-release validate-commit-msg coveralls \
rimraf prettier chalk -D

# Export new created fodler name to caller
echo $PROJECT_NAME
